name: Build musl-cross-make

on:
  push:            # triggers on any push to any branch
  workflow_dispatch: # enables manual trigger from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make gcc g++ git

      - name: Clone musl-cross-make
        run: |
          git clone https://github.com/richfelker/musl-cross-make.git

      - name: Add config.mak with TARGET
        run: |
          cd musl-cross-make
          echo 'TARGET = x86_64-linux-musl' > config.mak

      - name: Build musl-cross-make
        run: |
          cd musl-cross-make
          make
