name: Build musl-cross-make

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make gcc g++ git tar

      - name: Clone musl-cross-make
        run: |
          git clone https://github.com/richfelker/musl-cross-make.git

      - name: Add config.mak with TARGET and OUTPUT (absolute path)
        run: |
          cd musl-cross-make
          ABS_OUTPUT="${GITHUB_WORKSPACE}/build"
          echo "TARGET = x86_64-linux-musl" > config.mak
          echo "OUTPUT = ${ABS_OUTPUT}" >> config.mak

      - name: Build musl-cross-make
        run: |
          cd musl-cross-make
          make all -j$(nproc)

      - name: Install musl-cross-make to build/
        run: |
          cd musl-cross-make
          make install

      - name: Determine platform info and create tarball
        id: platform
        run: |
          ARCH=$(uname -m)
          if [[ "$ARCH" == "x86_64" ]]; then
            BITS="x64"
          else
            BITS="x32"
          fi
          OS=${{ runner.os }}
          FILENAME="musl-cross-toolchain-${BITS}-${OS}.tar.gz"
          echo "filename=$FILENAME" >> "$GITHUB_OUTPUT"
          tar -czf "$FILENAME" -C "$GITHUB_WORKSPACE" build

      - name: Upload tarball artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.platform.outputs.filename }}
          path: ${{ steps.platform.outputs.filename }}
